### ISSUE TITLE
PyPI source distribution missing requirements.txt

### ISSUE THREAD

**Issue by allanadair** [kubernetes-incubator/client-python#361] opened 2017-10-16 12:32 UTC
setup.py depends on the presence of requirements.txt and test-requirements.txt, however these files are not included within the source distribution on PyPI.

This means that the package cannot be installed from the source distribution.

**Comment by Ajay191191** [comment] 2017-10-18 18:19
I can confirm this. setup.py fails to install because of the absence of those 2 files.

**Comment by mbohlool** [comment] 2017-10-18 20:54
@allanadair Thanks for reporting this. If you know a quick fix for this, I appreciate it if you send a PR for it.

**Closed** 2017-10-19 17:51 UTC
Labels: help-needed
