### ISSUE TITLE
Watching multiple resource types

### ISSUE THREAD

**Issue by drdivano** [kubernetes-incubator/client-python#380] opened 2017-11-06 07:40 UTC
I am attempting to create an ingress controller in python (for Varnish). As far as I understand I have to simultaneously watch for events from ingresses, endpoints, and probably from pods to control session affinity.

Is there a way to do this cleanly (besides polling)?

**Comment by tomplus** [comment] 2017-11-06 10:01
I'm afraid not, see https://github.com/kubernetes-incubator/client-python/issues/30

**Comment by mbohlool** [comment] 2017-11-11 11:08
yes, duplicate of #30. Hopefully we get to that soon.

**Closed by mbohlool** 2017-11-11 11:08 UTC
