### ISSUE TITLE
Release 1.0 stable

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-incubator/client-python#130] opened 2017-02-21 22:22 UTC
I think the client is stable enough for first release. I've release ~~Beta 2~~ Beta 3. Please give it a try and report back any problems. If there is no serious issues, I will release 1.0 in a week (target 2/28/2017).

**Comment by mrmcmuffinz** [comment] 2017-02-23 14:32
Actually to be clear it is `1.0.0b3` there were some missing requirements in setup.py which broke the build and were fixed in `1.0.0b3`

**Comment by dims** [comment] 2017-02-23 14:43
agree 1.0.0b3 should be good (https://github.com/kubernetes-incubator/client-python/compare/v1.0.0b2...v1.0.0b3)

**Comment by mbohlool** [comment] 2017-02-23 21:12
Updated first comment to to beta 3. I wrote it before we found the bug in beta 2 setup.

**Comment by mrmcmuffinz** [comment] 2017-02-24 03:40
Few questions:
1. How do you want us to report issues, open up the issue right away or report it first elsewhere and then if it is valid open it up?
2. Are we going to see up to date examples with the better approach of setting up/loading the kubernetes config?
3. I actually do have an situation where I'm not sure if it counts as an issue but I my problem is as such. When accessing the namespace hardware information my expectation is that I should be able to access the dictionary keys as ordinary members but it does not seem the case for the below two cases:
```python
 1. response.spec.containers[0].resources.limits["cpu"]
 2. response.spec.containers[0].resources.limits["memory"] 
```
Am I right to have the prior expectation or is this working as intended?

**Comment by mbohlool** [comment] 2017-02-24 12:27
1. I think like the rest of kubernetes, slack channel of SIG is the best starting point, then maybe creating issues.
2. We have some examples on that, what do you have in mind? PR is welcome :)
3. That should work if `cpu` or `memory` is in that map (that is not there all the time). Check `if "cpu" in ...` first.

**Comment by dims** [comment] 2017-02-24 13:30
In addition to what @mbohlool said, would love to see code snippets in the issues, so we can then turn that into unit or e2e tests quickly.

Thanks,
dims

**Comment by mrmcmuffinz** [comment] 2017-02-24 21:10
I'm on the kubernetes.slack.com, is there a dedicated channel for talking about this codebase?

**Comment by mrmcmuffinz** [comment] 2017-02-24 23:50
Follow up question, what will the protocol be now for new releases, lets say we find a bug and a fix goes in, when do we bump it?

**Comment by mbohlool** [comment] 2017-02-25 01:42
Depends on the problem and how severe it is. We can decide on a case by case basis for now I guess.

**Comment by mbohlool** [comment] 2017-02-26 09:18
Look like I need to call the stable release 1.0.1 to make sure it is bigger than 1.0.0b*.

**Comment by mrmcmuffinz** [comment] 2017-02-26 14:05
Can we go with v1.1.0 instead? My reasoning is that if we go off of http://semver.org/ we are releasing a minor change and so the minor should be bumped once we deem it fit for public consumption.  If we see that there are any issues then we deliver a fix and that would be considered a patch such as the recent delivery we did on exec and extra data from the channel.

**Comment by dims** [comment] 2017-02-26 15:48
@mbohlool 1.0.0 is higher than 1.0.0b in all the typical tools like pip etc. So we should be good. if we do see a problem, then we can release a 1.0.1

**Comment by mrmcmuffinz** [comment] 2017-02-27 14:22
Hi @mbohlool & @dims, which release version will we be going with?

**Comment by mbohlool** [comment] 2017-02-27 21:52
@dims Sure, I was wondering if we can just skip any problem by using 1.0.1, but if packaging tools understand that 1.0.0 > 1.0.0b then we should be good.

**Comment by WilliamDenniss** [comment] 2017-02-27 22:23
@mrmcmuffinz It's valid semver to have a beta suffix which is deemed less than the final release with the unsuffixed number http://semver.org/#spec-item-11

**Comment by mrmcmuffinz** [comment] 2017-02-28 01:06
@mbohlool ok, though how does that fit with what is in in [CHANGELOG.md ](https://github.com/kubernetes-incubator/client-python/blob/master/CHANGELOG.md#v101) as I see `v1.0.1`? 

@WilliamDenniss ok, I don't disagree with that statement nor do I see where I made the opposite claim. Could you please clarify where the misunderstanding is?

**Comment by mbohlool** [comment] 2017-02-28 01:34
@mrmcmuffinz I will change that.

**Comment by mbohlool** [comment] 2017-03-01 23:41
The release is live: https://github.com/kubernetes-incubator/client-python/releases/tag/v1.0.0

**Closed** 2017-04-26 22:54 UTC
